server:
  port: 8080
spring:
#  redis:
#    host: 47.96.110.70
#    port: 6379
#    time-out: 10000
#    password: 123456
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        min-idle: 0
#        max-wait: 10000
  datasource:
    url: jdbc:mysql://localhost:3306/plc_demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  typeAliasesPackage: platform.plc.platform.entity
  mapperLocations: classpath:mapper/*Mapper.xml
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    com.plc.platform.dao: debug
